[project]
name = "newsresearch"
version = "0.1.0"
description = "newsresearch using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.95.0,<1.0.0"
]

[project.scripts]
newsresearch = "newsresearch.main:run"
run_crew = "newsresearch.main:run"
train = "newsresearch.main:train"
replay = "newsresearch.main:replay"
test = "newsresearch.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

